### ISSUE TITLE
pysqlite2/sqlite3

### ISSUE THREAD

**Issue by dakl** [robinandeer/chanjo#167]
Hi, 

After installing chanjo (`pip install chanjo`), I did `chanjo init` which worked fine, but then

```
$ chanjo db setup
[2016-02-03 10:30:21,419] INFO    : chanjo.cli.root          : version 3.2.1
Traceback (most recent call last):
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/bin/chanjo", line 11, in <module>
    sys.exit(root_command())
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 1024, in invoke
    Command.invoke(self, ctx)
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/chanjo/cli/database.py", line 17, in db
    context.db = Store(uri=context.obj['database'])
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/chanjo/store/core.py", line 55, in __init__
    self.connect(uri, debug=debug)
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/chanjo/store/core.py", line 79, in connect
    self.engine = create_engine(db_uri, **kwargs)
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/daniel.klevebring/.pyenv/versions/2.7.8/lib/python2.7/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 339, in dbapi
    raise e
ImportError: No module named pysqlite2
```

```
$ python -V
Python 2.7.8
```

Should this import `sqlite3` instead? (http://stackoverflow.com/questions/12044548/importerror-no-module-named-pysqlite2)

cheers

**Comment by dakl** [comment]
Omg omg omg. 

Latest breaking news. 

My bad. Closing.

**Comment by robinandeer** [comment]
hahah,
no worries, happy that plp are trying it out ;)
