### ISSUE TITLE
Error on link command from demo

### ISSUE THREAD

**Issue by nuin** [robinandeer/chanjo#174]
I am getting this error 

```
~/chanjo-demo  chanjo link sample1.coverage.bed
[2016-02-21 00:32:49,728] INFO    : chanjo.cli.root          : version 3.3.0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/base.py", line 379, in _entity_descriptor
    return getattr(entity, key)
AttributeError: type object 'Exon' has no attribute 'chrom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/chanjo", line 11, in <module>
    sys.exit(root_command())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/chanjo/cli/link.py", line 21, in link
    link_elements(chanjo_db, bed_stream)
  File "/usr/local/lib/python3.5/site-packages/chanjo/cli/link.py", line 28, in link_elements
    for index, stat in enumerate(stats):
  File "/usr/local/lib/python3.5/site-packages/chanjo/load/link.py", line 9, in <genexpr>
    exons = (row(session, data) for data in row_data)
  File "/usr/local/lib/python3.5/site-packages/chanjo/load/link.py", line 16, in row
    exon_obj = get_or_build_exon(session, data)
  File "/usr/local/lib/python3.5/site-packages/chanjo/load/utils.py", line 26, in get_or_build_exon
    exon_obj = session.query(Exon).filter_by(**exon_filters).first()
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 1510, in filter_by
    for key, value in kwargs.items()]
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 1510, in <listcomp>
    for key, value in kwargs.items()]
  File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/base.py", line 383, in _entity_descriptor
    (description, key)
sqlalchemy.exc.InvalidRequestError: Entity '<class 'chanjo.store.models.Exon'>' has no property 'chrome'
```

Any ideas?

**Comment by robinandeer** [comment]
I will look into it :)

**Comment by robinandeer** [comment]
I had missed to update this command as I improved the speed of the load command - very nice catch, thank you for the bug report!
