### ISSUE TITLE
Error with chanjo link

### ISSUE THREAD

**Issue by nuin** [robinandeer/chanjo#182]
Hi

I am having an error while trying to run `chanjo link` with a Sambamba generated coverage file. Here is the output:

`````` python
chanjo link exons.covergae.bed                                                                                   [ruby-2.0.0p648]
[2016-06-08 11:00:03,146] INFO    : chanjo.cli.root          : version 3.4.1
Traceback (most recent call last):
  File "/usr/local/bin/chanjo", line 11, in <module>
    sys.exit(root_command())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/chanjo/cli/link.py", line 38, in link
    link_elements(chanjo_db, bed_stream)
  File "/usr/local/lib/python2.7/site-packages/chanjo/cli/link.py", line 48, in link_elements
    for index, stat in enumerate(stats):
  File "/usr/local/lib/python2.7/site-packages/chanjo/load/link.py", line 9, in <genexpr>
    exons = (row(session, data) for data in row_data)
  File "/usr/local/lib/python2.7/site-packages/chanjo/parse/bed/parse.py", line 20, in chanjo
    yield expand_row(row)
  File "/usr/local/lib/python2.7/site-packages/chanjo/parse/bed/parse.py", line 49, in expand_row
    raise BedFormattingError('invalid BED syntax, score column is int')
chanjo.exc.BedFormattingError: invalid BED syntax, score column is int```

Any help appreciated.

``````

**Comment by robinandeer** [comment]
Hi!

have you checked if the file is TAB or space separated? I find this is many times the issue. Sambamba will handle both okey but chanjo is stricter and requires TAB separated columns.

If you can provide a sample of the coverage file I will look into it further!
