### ISSUE TITLE
chanjo generates errors instead of help text

### ISSUE THREAD

**Issue by henrikstranneheim** [robinandeer/chanjo#187]
```
$chanjo
Traceback (most recent call last):
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/bin/chanjo", line 11, in <module>
    load_entry_point('chanjo==4.0.0', 'console_scripts', 'chanjo')()
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/click/core.py", line 695, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/click/core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/click/core.py", line 1009, in parse_args
    echo(ctx.get_help(), color=ctx.color)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/click/core.py", line 495, in get_help
    return self.command.get_help(self)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/click/core.py", line 824, in get_help
    self.format_help(ctx, formatter)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/click/core.py", line 839, in format_help
    self.format_options(ctx, formatter)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/click/core.py", line 950, in format_options
    self.format_commands(ctx, formatter)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/click/core.py", line 995, in format_commands
    cmd = self.get_command(ctx, subcommand)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/chanjo/cli.py", line 42, in get_command
    return commands[name].load()
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/mnt/hds/proj/cust003/develop/modules/miniconda2/envs/mip4.1/lib/python2.7/site-packages/chanjo/init/cli.py", line 6, in <module>
    from path import path
ImportError: cannot import name path
```

**Comment by moonso** [comment]
This is because `path` is not installed. Try `pip install path` and try again.
We should include this in requirements if it is not already done

**Comment by henrikstranneheim** [comment]
```
pip install path
Downloading/unpacking path
  Could not find any downloads that satisfy the requirement path
Cleaning up...
No distributions at all found for path
Storing complete log in /home/henrik.stranneheim/.pip/pip.log
```

**Comment by moonso** [comment]
Sorry, it should probably be `pip install Path`

**Comment by henrikstranneheim** [comment]
Nope 😄 
```
$ pip install Path
Downloading/unpacking Path
  Could not find any downloads that satisfy the requirement Path
Cleaning up...
No distributions at all found for Path
Storing complete log in /home/henrik.stranneheim/.pip/pip.log
```

**Comment by moonso** [comment]
Ok let's wait for @robinandeer then

**Comment by robinandeer** [comment]
yeah it's called `path.py` but we need to update the code to correct the import
