### ISSUE TITLE
Problems when loading bed-file using config

### ISSUE THREAD

**Issue by mjlarsen** [robinandeer/chanjo#189]
Hi

I have tried to get chanjo up and running. Sambamba is installed using conda and chanjo using pip. 

conda install -c bioconda sambamba
pip install chanjo

After running chanjo init it tells me to run chano –config, however doing that returns the following error:

```
martin@ubuntu:~$ chanjo init test
2017-05-17 00:19:25 ubuntu chanjo.init.cli[11864] INFO setting up chanjo under: /home/martin/test
Bootstrap CCDS transcript BED? [y/N]: y
2017-05-17 00:19:27 ubuntu chanjo.init.bootstrap[11864] INFO downloading... [https://s3.eu-central-1.amazonaws.com/chanjo/ccds15.grch37p13.extended.bed.zip]
2017-05-17 00:19:30 ubuntu chanjo.init.bootstrap[11864] INFO extracting BED file...
2017-05-17 00:19:30 ubuntu chanjo.init.bootstrap[11864] INFO removing BED archive...
2017-05-17 00:19:30 ubuntu chanjo.init.cli[11864] INFO configure new chanjo database: sqlite:////home/martin/test/chanjo.coverage.sqlite3
2017-05-17 00:19:30 ubuntu chanjo.store.api[11864] INFO created tables: transcript, sample, transcript_stat
2017-05-17 00:19:30 ubuntu chanjo.init.cli[11864] INFO writing config file: /home/martin/test/chanjo.yaml
Chanjo bootstrap successful! Now run:
chanjo --config /home/martin/test/chanjo.yaml link /home/martin/test/ccds.15.grch37p13.extended.bed
martin@ubuntu:~$ chanjo --config /home/martin/test/chanjo.yaml link /home/martin/test/ccds.15.grch37p13.extended.bed
adding transcripts  [------------------------------------]    0%
Traceback (most recent call last):
  File "/home/martin/miniconda3/bin/chanjo", line 11, in <module>
    sys.exit(root())
  File "/home/martin/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/martin/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/martin/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/martin/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/martin/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/martin/miniconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/martin/miniconda3/lib/python3.6/site-packages/chanjo/load/cli.py", line 60, in link
    for tx_model in bar:
  File "/home/martin/miniconda3/lib/python3.6/site-packages/click/_termui_impl.py", line 259, in next
    rv = next(self.iter)
  File "/home/martin/miniconda3/lib/python3.6/site-packages/chanjo/load/link.py", line 24, in <genexpr>
    models = (make_model(tx_id, exons) for tx_id, exons in transcripts.items())
  File "/home/martin/miniconda3/lib/python3.6/site-packages/chanjo/load/link.py", line 40, in make_model
    gene_id = int(exons[0]['elements'][transcript_id]['gene_id'])
ValueError: invalid literal for int() with base 10: '-'
martin@ubuntu:~$

```

**Comment by robinandeer** [comment]
Hi!

I'm sorry about this - we are lagging behind on updating the pre-calculated resources for setting up Chanjo :(

Defining exons, transcripts, and genes is a very tricky topic and while we started out with CCDS as the base we've come to realize that this isn't covering enough genes to be clinically relevant.

@moonso has therefore been working a lot to come up with an alternative based on HGNC and Ensembl which we are now using in our production pipeline.

I will make a push and update the Chanjo resources to reflect this!

Thanks for your feedback
